disabled_rules: # rule identifiers to exclude from running
  - line_length
  - function_body_length
  - trailing_whitespace
  - vertical_whitespace
  - file_length
  - trailing_newline
  - force_cast
  - large_tuple
  - identifier_name
  - multiple_closures_with_trailing_closure
  - legacy_constructor
  - type_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - "*/*/*.generated.swift" # dependent on file hierarchy, no fix as of yet