# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  xcversion(version: "11.3")
end

platform :ios do
  desc 'Runs the unit tests in IntrospectTests'
  lane :unit_test do
    scan(scheme: "IntrospectTests")
  end

  desc 'Runs the UI tests in IntrospectUITests'
  lane :ui_test do
    scan(scheme: "IntrospectUITests")
  end
end